# --- HOSTS ---
hosts.host_id: hosts.host_id
hosts.dealer_id: hosts.dealer_id
hosts.programmatic_id: hosts.programmatic_id
hosts.user_id: hosts.user_id
hosts.name: hosts.name
hosts.address: hosts.address
hosts.city: hosts.city
hosts.state: hosts.state
hosts.region: hosts.region
hosts.country: hosts.country
hosts.postal_code: hosts.postal_code
hosts.latitude: hosts.latitude
hosts.longitude: hosts.longitude
hosts.time_zone: hosts.time_zone
hosts.store_hours: hosts.store_hours
hosts.venue_type: hosts.venue_type
hosts.monthly_traffic: hosts.monthly_traffic
hosts.avg_dwell_time: hosts.avg_dwell_time
hosts.avg_ticket: hosts.avg_ticket
hosts.demographics: hosts.demographics
hosts.internet: hosts.internet
hosts.install_date: hosts.install_date
hosts.date_created: hosts.date_created
hosts.date_updated: hosts.date_updated
hosts.status: hosts.status
hosts.category: hosts.category
hosts.vistar_venue_id: hosts.vistar_venue_id
hosts.contact_person: hosts.contact_person
hosts.contact_number: hosts.contact_number

# --- DEALERS ---
dealers.dealer_id: dealers.dealer_id
dealers.generated_id: dealers.generated_ID
dealers.business_name: dealers.business_name
dealers.contact_person: dealers.contact_person
dealers.contact_number: dealers.contact_number
dealers.address: dealers.address
dealers.city: dealers.city
dealers.state: dealers.state
dealers.region: dealers.region
dealers.zip: dealers.zip
dealers.user_id: dealers.user_id
dealers.dealer_type: dealers.dealer_type
dealers.license_count: dealers.license_count
dealers.player_count: dealers.player_count
dealers.dealer_id_alias: dealers.dealer_id_alias
dealers.start_date: dealers.start_date
dealers.date_created: dealers.date_created
dealers.date_updated: dealers.date_updated
dealers.status: dealers.status
dealers.logo: dealers.logo

# --- LICENSES ---
licenses.license_id: licenses.license_id
licenses.license_key: licenses.license_key
licenses.mac_address: licenses.mac_address
licenses.is_registered: licenses.is_registered
licenses.is_activated: licenses.is_activated
licenses.dealer_id: licenses.dealer_id
licenses.host_id: licenses.host_id
licenses.internet_type: licenses.internet_type
licenses.internet_speed: licenses.internet_speed
licenses.date_created: licenses.date_created
licenses.date_updated: licenses.date_updated
licenses.install_date: licenses.install_date
licenses.player_status: licenses.player_status
licenses.pi_status: licenses.pi_status
licenses.display_status: licenses.display_status
licenses.server_version: licenses.server_version
licenses.ui_version: licenses.ui_version
licenses.screenshot: licenses.screenshot
licenses.reboot_time: licenses.reboot_time
licenses.tv_brand: licenses.tv_brand
licenses.public_ip: licenses.public_ip
licenses.prev_public_ip: licenses.prev_public_ip
