resolvers:
  licenses.dealer_id:
    via_table: dealers
    return_column: dealers.dealer_id
    match:
      field: dealers.dealer_name
      mode: ilike_contains
      escape: "\\"

  hosts.dealer_id:
    via_table: dealers
    return_column: dealers.dealer_id
    match:
      field: dealers.dealer_name
      mode: ilike_contains
      escape: "\\"

  hosts.host_id:
    via_table: hosts
    return_column: hosts.host_id
    match:
      field: hosts.host_name
      mode: ilike_contains
      escape: "\\"
